### ISSUE TITLE
Alternative view of Calendar class

### ISSUE THREAD

**Issue by mmmveggies** [DanielFGray/ncal#4]
No suggestion, just my take on this code problem.

http://jsfiddle.net/84042tz9/1/

**Comment by DanielFGray** [comment]
so, right aligned?

**Comment by mmmveggies** [comment]
I was talking more about using the date object as much as possible and not using a for loop

**Comment by DanielFGray** [comment]
Ohhh, please forgive me, I saw "view" and only looked at presentation.

I agree that I could probably optimize and make use of more of `Date()`s internals, I just wanted to whip up something quick.

**Comment by DanielFGray** [comment]
I am reading through your code, and like your approach. I might merge it in once I read through it a bit more.
